#app
server:
  port: 8020
  session:
    timeout: 1800
  connection-timeout:  60000
#spring
spring:
  application:
    name: springboot
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
        
  profiles:
    active: dev

  jackson:
    date-format: YYYY-MM-DD
    joda-date-time-format: YYYY-MM-DD HH:mm:ss
  cache:
    ehcache:
      config: classpath:ehcache.xml

mybatis:
  mapper-locations: com/yx/entity/mapper/*Mapper.xml
logging:
  level: 
    org.springframework.web: DEBUG
    com.nico.web: TRACE
    com.yx.youchubank: INFO
  path: /var/logs
  file: /logs/webmagic.log
---
spring:
   profiles: dev
   datasource:
     url: jdbc:mysql://192.168.254.108:3306/webmagic?useUnicode=true&characterEncoding=utf-8
     username: root
     password: 123456
     driver-class-name: com.mysql.jdbc.Driver
     type: com.alibaba.druid.pool.DruidDataSource
# 初始化大小，最小，最大  
     initialSize: 5
     minIdle: 5
     maxActive: 20
# 配置获取连接等待超时的时间  
     maxWait: 60000
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒  
     timeBetweenEvictionRunsMillis: 60000
# 配置一个连接在池中最小生存的时间，单位是毫秒  
     minEvictableIdleTimeMillis: 300000
# 校验SQL，Oracle配置               validationQuery: SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用  
     validationQuery: SELECT 'x'
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
# 打开PSCache，并且指定每个连接上PSCache的大小  
     poolPreparedStatements: true
     maxPoolPreparedStatementPerConnectionSize: 20
# 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙  
     filters: stat,wall,log4j
# 通过connectProperties属性来打开mergeSql功能；慢SQL记录  
     connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
# 合并多个DruidDataSource的监控数据  
     useGlobalDataSourceStat: true
   redis:
        #database: 2
        host: 192.168.254.108
        port: 6379
        password: 
        pool:
          max-active: 100
          max-idle: 10
          max-wait: 100000
        timeout: 5000
        commandTimeout: 5000
sendserver:
   HOST: 'http://211.147.234.85:8081/Consensus/Client/'
   MAC: '52:54:00:1D:D2:FE'
   PWD: 123456
   JSON: '{"type":1,"mac":"52:54:00:1D:D2:FE","synonym":{"邮储银行":"邮政储蓄银行 邮储行","湖南":"长沙 湘潭 株洲 邵阳 岳阳 常德 益阳 郴州 衡阳 娄底 怀化 永州 张家界 湘西"},"depth":20,"task":{"bean_status":null,"id":98,"title":"邮储银行","categoryId":42,"attention":0.3,"mustword":"湖南 邮储银行","orword":"","notword":"","issnapshot":null,"isdownphoto":null,"enable":1,"monitortime":180,"createon":"1551150726000","createby":"youchubank","updateby":"youchubank","updateon":"1551150726000","name":"常规监测","companyName":"湖南邮储银行","companyId":19,"sitetype":null},"targetsite":{"siteCode":"N0000759","sysType":0,"scanfrequency":180,"title":"百度网页","sitetype":"1","sleep":2,"serialVersionUID":1,"depth":10,"id":476,"state":0},"isdownphoto":0,"warning":{"serialVersionUID":1,"replyCount":1000,"clickCount":1000,"citedCount":1000},"id":"23654-21","targetsiteid":476,"state":3,"time":1551150726154,"taskid":98}'
   DETAIL_JSON: '{"item":{"Url":"http://hunan.sina.com.cn/finance/2019-04-29/detail-ihvhiewr8950771.shtml"},"exist_templates":2,"cuid":"19-98-b6911cb293c4a770","type":1,"mac":"52:54:00:1D:D2:FE","depth":1,"task":{"mustword":"邮储银行","orword":"长沙 湘潭 株洲 邵阳 岳阳 常德 益阳 郴州 衡阳 娄底 怀化 永州 张家界 湘西","title":"湖南 邮储银行","notword":"","serialVersionUID":1,"createby":"100000","companyId":"19","monitortime":1800,"updateby":"100000","enable":1,"attention":"0.3","createon":1539849934000,"id":"98","updateon":1539855506000,"categoryId":"42"},"targetsite":{"sleep":2,"serialVersionUID":1,"siteCode":"N0001770","depth":5,"sysType":0,"scanfrequency":60,"id":514,"state":0,"title":"新湖南","sitetype":1,"isproxy":0,"errorMsg":""},"isdownphoto":0,"warning":{"serialVersionUID":1,"replyCount":1000,"clickCount":1000,"citedCount":1000},"id":23601,"targetsiteid":1075,"state":3,"time":1540780348164,"detail":{"feature":1,"Content":"<p>　　4月25日，邮储银行湖南省分行纪委书记带领机关部分员工走进湖南省反腐倡廉警示教育基地——长沙监狱，接受警示教育。</p> \n<div class=\"img_wrapper\"> \n <img src=\"http://n.sinaimg.cn/hunan/transform/60/w550h310/20190429/ukBV-hwfpcxm9711069.png\" alt=\"\" data-link=\"\"> \n <span class=\"img_descr\"></span> \n</div> \n<p>　　87名来自省分行机关的重要部门负责人、业务骨干在监狱工作人员引导下，参观了服刑人员工作区，切身感受了高墙与现实的巨大反差，随后观看了“反腐倡廉警示教育图片展览”及警示教育片《忠诚与背叛》。这部反腐大片以湖南省查处的严重违纪违法的省管高层干部为“主角”，一系列触目惊心的案例，落马干部声泪俱下、现身说法，使参观人员体会到“贪廉一念间，荣辱两世界”的真谛，一个党员干部不管地位多高、权力多大，只要违法乱纪，终究逃不脱党纪国法的严厉制裁，以身试法者必亡。</p> \n<div class=\"img_wrapper\"> \n <img src=\"http://n.sinaimg.cn/hunan/transform/713/w438h275/20190429/oNzg-hwfpcxm9712143.png\" alt=\"\" data-link=\"\"> \n <span class=\"img_descr\"></span> \n</div> \n<p>　　此次警示教育活动是邮储银行湖南省分行2019年“开展案件警示教育活动”反腐倡廉主题教育系列活动之一。下一步，湖南省分行纪委监察部还将通过学习典型案例通报、开展党风廉政宣传月活动、节假日期间加强作风建设提醒和监督检查、播放电子廉政海报、邀请专家集中授课等宣传教育活动，引导党员干部增强底线、红线意识，不断强化党纪法规观念，提高拒腐防变能力。（杨琼英 杨伊媛）</p> \n<style>\n\t\t\t.article-editor {\n    margin-top: 5px;\n    text-align: right;\n}\t\n\t.article-body  img{\n\t\tmax-width:550px;\n\t}\n\n\t\t</style> \n<div class=\"article_video\" style=\"margin:30px auto 0px;width:300px;height:250px;\"> \n <ins class=\"sinaads\" data-ad-pdps=\"PDPS000000031042\"></ins> \n <script>(sinaads = window.sinaads || []).push({});</script> \n <!--\t<img src=\"http://n.sinaimg.cn/shanxi/test0505/WenZhangXia.jpg\"style=\"width:100%;\"/>--> \n</div>","Title":"警钟长鸣——邮储银行湖南省分行开展参观监狱 警示教育活动","siteName":"新浪网","warning":0,"location":"http://hunan.sina.com.cn/finance/2019-04-29/detail-ihvhiewr8950771.shtml","From":"综合","pubDateTime":"2019-04-29 00:00:00"},"taskid":98,"statusCode":"200"}'